- config.ts
Content sync was not working when this was set as a subdeployment of plh_facilitator. I've made this a stand alone deployment for now, potentially should revisit this later.
> update config to be stand alone deployment

- app_data/sheets/contents.json
- app_data/sheets/data_list/app_config_language_list/language.json
- app_data/sheets/data_list/article_data.json
- app_data/sheets/data_list/state_data.json
- app_data/sheets/global/article_global.json
- config.ts
- add file format to image references
> content: 1.1.3

- app_data/sheets/template/article.json
- config.ts
> content: 1.1.7

- app_data/sheets/contents.json
- app_data/sheets/data_list/privacy_policy.json
- app_data/sheets/data_list/terms_and_conditions.json
- app_data/sheets/global/legal_terms.json
- app_data/sheets/global/profile_global.json
- app_data/sheets/template/add_coparent.json
- app_data/sheets/template/data_collection.json
- app_data/sheets/template/existing_coparent.json
- app_data/sheets/template/existing_parent.json
- app_data/sheets/template/existing_parent_profile.json
- app_data/sheets/template/in_person_form.json
- app_data/sheets/template/legal_terms/privacy_policy.json
- app_data/sheets/template/legal_terms/terms_and_conditions.json
- app_data/sheets/template/new_parent_profile.json
- app_data/sheets/template/parent_profile.json
- app_data/sheets/template/parents_data.json
- app_data/sheets/template/profile_groups.json
- app_data/sheets/template/time_question.json
- app_data/sheets/template/virtual_form.json
- config.ts
- integrate terms and conditions
- integrate privacy policy
> content: 1.1.11

- app_data/sheets/contents.json
- app_data/sheets/data_list/app_section_data.json
- app_data/sheets/data_list/package_data.json
- app_data/sheets/data_list/profile_section_data.json
- app_data/sheets/global/deployment_global.json
- app_data/sheets/global/deployment_global_my.json
- app_data/sheets/template/generated/help_group.json
- app_data/sheets/template/profile_about.json
- config.ts
Additional translatable strings
Fix MY states
> content: 1.1.17

- app_data/sheets/contents.json
- app_data/sheets/data_list/profile_section_data.json
- app_data/sheets/global/deployment_global.json
- app_data/sheets/global/deployment_global_my.json
- app_data/sheets/global/profile_global.json
- app_data/sheets/template/footer_my.json
- app_data/sheets/template/parent_group.json
- app_data/sheets/template/parent_profile.json
- app_data/sheets/template/profile.json
- app_data/sheets/template/profile_group.json
- app_data/sheets/template/profile_groups.json
- config.ts
- custom home screen icon (closes https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/34)
- correct buttons in profile section
> content: 1.1.20

- app_data/sheets/data_list/state_data.json
- app_data/sheets/global/profile_global.json
- app_data/sheets/template/existing_parent.json
- app_data/sheets/template/existing_parent_profile.json
- app_data/sheets/template/new_parent_profile.json
- app_data/sheets/template/parent_group.json
- app_data/sheets/template/parent_profile.json
- app_data/sheets/template/profile_group.json
- app_data/sheets/template/profile_groups.json
- config.ts
Ability to add parents in Parent Group section
> content: 1.1.22

- app_data/sheets/contents.json
- app_data/sheets/data_list/report_data.json
- app_data/sheets/global/profile_global.json
- app_data/sheets/template/data_collection.json
- app_data/sheets/template/existing_parent.json
- app_data/sheets/template/existing_report.json
- app_data/sheets/template/in_person_form.json
- config.ts
> content: 1.1.23

- app_data/sheets/global/profile_global.json
- app_data/sheets/template/delete_parent.json
- app_data/sheets/template/parent_profile.json
- config.ts
- Add pop-up warning ahead of deleting a parent
- Add `archived_parent_data` field
> content: 1.1.25

- app_data/sheets/data_list/article_data.json
- config.ts
> content: 1.1.33

- app_data/sheets/contents.json
- app_data/sheets/data_list/article_data.json
- app_data/sheets/data_list/lifecycle_actions/launch_actions.json
- app_data/sheets/global/debug_global.json
- app_data/sheets/template/app_update_complete.json
- app_data/sheets/template/in_person_form.json
- app_data/sheets/template/language_select.json
- app_data/sheets/template/legal_terms/accept_terms.json
- config.ts
- article data updates
- fixes to app launch sequence
> content: 1.1.34

- config.ts
PR updates deployment config to include error logging and db name
> Update config to include error logging and db name

- app_data/sheets/template/in_person_unreported.json
- app_data/sheets/template/virtual_unreported.json
- config.ts
- add phrase in virtual reporting pop-up when all reports have been submitted.
> content: 1.1.39

- app_data/sheets/template/parent_profile.json
- config.ts
- Validation of ParentText ID (closes https://github.com/IDEMSInternational/plh-facilitator-app-my-content/issues/37)
[screen-capture (68).webm](https://github.com/IDEMSInternational/plh-facilitator-app-my-content/assets/74557272/00ecf902-dd1b-4112-ac2e-58e5e251b515)
- Content version (i.e. app release version) visible in side menu and accessible in database
> content: 1.1.42

- app_data/sheets/template/legal_terms/accept_terms.json
- config.ts
- fix bug on accept_terms page for iPhone web browser users
> content: 1.1.48

- app_data/sheets/contents.json
- app_data/sheets/template/in_person_unreported.json
- app_data/sheets/template/virtual_unreported.json
- app_data/translations/contents.json
- config.ts
Refactor following https://github.com/IDEMSInternational/parenting-app-ui/pull/2135
> content: 1.1.50

- app_data/sheets/contents.json
- app_data/sheets/data_list/article_data.json
- app_data/sheets/data_list/closing_extra_data.json
- app_data/sheets/data_list/home_screen_section_data.json
- app_data/sheets/data_list/onboarding_extra_data.json
- app_data/sheets/data_list/organisation.json
- app_data/sheets/data_list/report_data.json
- app_data/sheets/template/virtual_form.json
- config.ts
- insert additional question in the whatsapp reporting form (progress towards https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/44)
- add additional content to onboarding and closing forms as data lists (ahead of syncing to Crowdin)
- remove duplicate mention of UNICEF
- minor fixes to article_data
> content: 1.1.55

- app_data/sheets/contents.json
- app_data/sheets/template/data_collection.json
- app_data/sheets/template/extra_onboarding.json
- app_data/sheets/template/in_person_unreported.json
- app_data/sheets/template/toggle_bar_question.json
- config.ts
- Ability to download PDFs (code version 0.16.23). This closes https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/41
- Amend reporting form interface so that only forms relevant to the content package show. This is progress towards https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/44
> content: 1.1.59

- app_data/sheets/data_list/report_closing_data.json
- app_data/sheets/data_list/report_onboarding_data.json
- app_data/sheets/template/in_person_form.json
- app_data/sheets/template/virtual_form.json
- config.ts
Content changes, closes https://github.com/IDEMSInternational/plh-facilitator-app-content/issues/44
WhatsApp
Onboarding
Closing
> content: 1.1.61

- app_data/sheets/template/article_launch_history.json
- config.ts
Minor change to format of `article_interaction_data` format, now also stores the article id inside: 
```
{
"faq_text_support":{
"article_id":"faq_text_support",
"launch_history":["2024-01-03T16:52:59"]
},
"what_is_safeguarding":{
"article_id":"what_is_safeguarding",
"launch_history":["2024-01-03T16:53:06"]
}
}
```
> content: 1.1.65

- app_data/sheets/contents.json
- app_data/sheets/data_list/pdf_data.json
- app_data/sheets/template/generated/pdf_group_masw_closing.json
- app_data/sheets/template/generated/pdf_group_masw_onboarding.json
- app_data/sheets/template/generated/pdf_group_masw_overview.json
- config.ts
> content: 1.1.66

- app_data/sheets/data_list/report_data.json
- app_data/sheets/template/data_collection.json
- config.ts
- reveal WhatsApp and Closing forms for MASW content package
> content: 1.1.67

- config.ts
Adds `android` and `ios` `app_id` and `app_name` properties for building to respective platforms via latest code.
> content: 1.1.71

- config.ts
> content: 1.1.73

- app_data/sheets/contents.json
- app_data/sheets/data_list/generated/article_data.json
- app_data/sheets/data_list/report_data.json
- app_data/sheets/data_pipe/article_filter.json
- app_data/sheets/template/data_collection.json
- app_data/sheets/template/in_person_unreported.json
- app_data/sheets/template/virtual_unreported.json
- config.ts
Refactor forms to also work for Mexico content (no longer Malaysia-specific)
> content: 1.1.74

- app_data/sheets/contents.json
- app_data/sheets/data_list/home_screen_section_data.json
- app_data/sheets/data_list/pdf_data.json
- app_data/sheets/template/app_menu.json
- app_data/sheets/template/generated/library_challenges.json
- app_data/sheets/template/menu_task_flow.json
- app_data/sheets/template/profile.json
- app_data/sheets/template/profile_login.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 2.1.7

- app_data/sheets/contents.json
- app_data/sheets/template/article_related.json
- app_data/sheets/template/library_article.json
- app_data/sheets/template/menu_task_card.json
- app_data/sheets/template/menu_task_flow.json
- config.ts
> content: 2.1.16

- app_data/sheets/template/download_header.json
- app_data/sheets/template/message_element.json
- app_data/sheets/template/parent_profile.json
- app_data/sheets/template/profile_groups.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 2.1.20

- app_data/sheets/contents.json
- app_data/sheets/template/menu_task_card.json
- config.ts
- reports/summary.json
- reports/summary.md
> content: 2.1.21

- app_data/sheets/contents.json
- app_data/sheets/data_list/a_intro.json
- app_data/sheets/data_list/a_sections.json
- app_data/sheets/data_list/modules.json
- app_data/sheets/template/add_coparent.json
- app_data/sheets/template/module_final.json
- app_data/sheets/template/profile_groups.json
- app_data/sheets/template/report_card.json
- config.ts
- reports/summary.json
- reports/summary.md
updated content and fixed issues with groups and parent
> content: 2.1.32

- app_data/sheets/contents.json
- app_data/sheets/data_list/a_resources.json
- app_data/sheets/template/library.json
- app_data/sheets/template/library_article.json
- app_data/sheets/template/message_element.json
- app_data/sheets/template/resource_element.json
- config.ts
Content sync - fixes issue where PDFs were not appearing
Also corrects margins on library page (following code PR changing margins)
> content: 2.2.2

- config.ts
Bumps version number to enable iOS release with updated code and same content
> ci: bump version number to 2.2.5
